# Personal clangd lsp configuration
CompileFlags:
  Compiler: g++
  Add:
    - -std=c++20
    - -Wall
    - -Wextra
    - -Wpedantic
Index:
  StandardLibrary: Yes
Diagnostics:
  ClangTidy:
    Add:
      - bugprone-*
      - cert-*
      - clang-analyzer-*
      - concurrency-*
      - cppcoreguidelines-*
      - google-*
      - linuxkernel-*
      - misc-*
      - modernize-*
      - performance-*
      - portability-*
      - readability-*
    Remove:
      - modernize-use-trailing-return-type
    CheckOptions:
      readability-identifier-naming.AbstractClassCase: CamelCase
      readability-identifier-naming.AbstractClassPrefix: I_
      readability-identifier-naming.ClassCase: CamelCase
      # readability-identifier-naming.GlobalConstantCase: UPPER_CASE
      # readability-identifier-naming.GlobalConstantPrefix: g
      readability-identifier-naming.ConstantCase: UPPER_CASE
      readability-identifier-naming.MemberCase: CamelCase
      readability-identifier-naming.MethodCase: CamelCase
      readability-identifier-naming.MemberPrefix: m
      readability-identifier-naming.MemberIgnoredRegexp: mp
      readability-identifier-naming.EnumCase: CamelCase
      readability-identifier-naming.EnumConstantCase: UPPER_CASE
      readability-identifier-naming.ScopedEnumConstantCase: UPPER_CASE
      readability-identifier-naming.PointerParameterCase: camelBack
      readability-identifier-naming.PointerParameterPrefix: p
      readability-identifier-naming.ConstantPointerParameterCase: CamelCase
      readability-identifier-naming.ConstantPointerParameterPrefix: cp
      readability-identifier-naming.ParameterCase: camelBack
      readability-identifier-naming.ConstantParameterCase: CamelCase
      readability-identifier-naming.ConstantParameterPrefix: c
      readability-identifier-naming.VariableCase: lower_case
