#!/bin/bash

# This script will install the different configurations to their correct location

PROGRAMS=("bash" "tmux" "vim" "clang")

# Verify that the XDG config location exists
if [[ ! -d "$XDG_CONFIG_HOME" ]]; then
    echo "\tCreating XDG_CONFIG_HOME directory"
    mkdir ~/.config
fi

echo "Installing dotfiles"
for program in ${PROGRAMS[@]}; do
    if [[ -f "${PWD}/${program}/setup" ]]; then
        "${PWD}/${program}/setup"
    fi
done
