" ---------- Basics ----------
" Disable backwards compatibility with vi
set nocompatible

" Automatic filetype detection
filetype plugin on
filetype indent on

" Enable syntax highlighting
syntax on

" Colorscheme
colorscheme desert

" Add numbers
set number

" Highlight current line
set cursorline

" Set default indentation values
set shiftwidth=4
set tabstop=4
set softtabstop=4
" Use spaces instead of tabs
set expandtab
" Auto indentation
set autoindent

" Show mode on last line
set showmode

" Use system clipboard
set clipboard=unnamedplus

" Keep cursor a few lines from the bottom
set scrolloff=8

" Change cursor to be a block in normal mode and line in insert mode
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

" ---------- Searching ----------
" Highlight Searches
set hlsearch
" Incremental highlight as you search
set incsearch
" Ignore case unless I am specifically using upper case
set ignorecase
set smartcase

" ---------- Key Bindings ----------
" Change leader key to space
let mapleader = " "

" Insert Mode Keymaps
inoremap jj <esc>

" Reload vimrc
nnoremap <leader>rv :source ~/.vimrc<CR>

" ---------- Autocommands ----------
" Use tabs instead of spaces for Makefiles
autocmd FileType make setlocal noexpandtab

" Syntax highlighting for bash_aliases and other aliases
autocmd BufNewFile,BufRead *aliases set ft=sh

" Indentation for yaml files
augroup yaml_Indentation
    autocmd!
    autocmd FileType yaml setlocal tabstop=2 softtabstop=2 shiftwidth=2
augroup END
