# File containing commonly used aliases for bash

# Alias for vim
alias v="vim"

# ls show all in log fromat with human readable size and colors
alias ls='ls -lah --color=auto'

# Colors
alias grep="grep --color=auto"

# Bashrc shortcuts
alias mbrc="vim $HOME/.bashrc"
alias sbr=". $HOME/.bashrc" 

# Git aliases
alias gs="git status"
alias ga="git add ."
alias gc="git commit"
alias gp="git push"

# Locations
alias dot="cd $HOME/.dotfiles"
