# File containing commonly used aliases for bash

# ls show all in log fromat with human readable size and colors
alias ls='ls -lah --color=auto'

# Bashrc shortcuts
alias mbrc="vim $HOME/.bashrc"
alias sbrc=". $HOME/.bashrc" 

# Locations
alias dot="cd $HOME/.dotfiles"
