# My .bash_profile
# Add environment variables and path variables you want to persist
# between different shell instances here.

# If the general profile exists, then source it
if [[ -f ${HOME}/.profile ]]; then
    source ${HOME}/.profile
fi

# If it is an interactive shell, then source .bashrc
if [ -n "$BASH_VERSION" -a -n "$PS1" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
        source "$HOME/.bashrc"
    fi
fi

