# File containing commonly used aliases for bash

# Alias for vim
alias v="vim"

# ls show all in log fromat with human readable size and colors
alias ls='ls --color=auto'
alias la='ls -lAh'
alias ll='ls -l'
alias lsme='ls | grep antoni'
alias llme='ll | grep antoni'

# Colors
alias grep="grep --color=auto"

# Bashrc shortcuts
alias mbrc="vim $HOME/.bashrc"
alias sbr=". $HOME/.bashrc"

# Chmod helper
alias chmodx='chmod u+x'

# ----- Git ----- #
alias gs='git status'

# ----- Python ----- #
alias pc='python3 -m venv .venv'
alias pa='source .venv/bin/activate'
alias pd='deactivate'

# Networking help
alias ls_ports='sudo lsof -i -P -n'

########## Locations ##########
alias dot='cd $HOME/.dotfiles'
alias repos='cd $HOME/repos'
alias docs='cd $HOME/Documents'
alias devel='cd ${HOME}/devel'
